### ISSUE TITLE
Compiled successfully. But the web page cannot be accessed.

### ISSUE THREAD

**Issue by 1457634627** [kiranbandi/synvisio#23]
I changed the port number in the webpack.config.js file and it shows that it has run successfully.

The port is open and the firewall is closed. But the web page is still inaccessible, do you know why?

**Comment by kiranbandi** [comment]
Hi,

I'm not sure what the issue is here as its hard to debug what's going on without an error log.
For local development with the webpack dev server, the firewall shouldnt matter as the system will be running on localhost. 
Was the webpage accessible before you changed the port number. 
Are you sure changing the port number was the issue. Did you try a different port number.
Also when your run "npm run start" there should be a link to the webpage in the terminal log. 
When you open that link what do you see in the browser?.
