### ISSUE TITLE
Create my own track file

### ISSUE THREAD

**Issue by Yung-Chien** [kiranbandi/synvisio#3]
Hi @kiranbandi ,
I'd like to upload my own MCScanX collinearity file and gff file to get the charming plot on your website. However I get an empty result that I think only collinearity file and gff file can not be recognized by dashborad and it seems that one or more track file is needed. So how could I generate my own track file? And what kind of files are required? 
Thanks in advances.
Yung

**Comment by kiranbandi** [comment]
Hi Yung,

A track file is not always necessary to get the basic plots on SynVisio. Track files are additional secondary files that can be used to augment existing plots with parallel tracks in the form of histograms, line charts, or scatter plots.

A possible reason for getting an empty result could be that there are no collinear blocks between the particular source and target that you have selected. Alternatively, some alignments may have been ignored because they are not in the right format. When uploading the files can you select the option "No" for the two questions on the upload page and try again. 

I can also debug the issue for you at my end, If you can share the collinearity and gff file that you used. Finally, sometimes an empty result can also be due to  format issues in the uploaded file so I have linked a [sample collinearity](https://github.com/kiranbandi/synvisio/blob/master/build/assets/files/bn_collinear.collinearity), [gff](https://github.com/kiranbandi/synvisio/blob/master/build/assets/files/bn_coordinate.gff), and [track file](https://github.com/kiranbandi/synvisio/blob/master/build/assets/files/bn_gene_count.txt) for your reference. 
 
Thanks,
Kiran

**Comment by Yung-Chien** [comment]
> Hi Yung,
> 
> A track file is not always necessary to get the basic plots on SynVisio. Track files are additional secondary files that can be used to augment existing plots with parallel tracks in the form of histograms, line charts, or scatter plots.
> 
> A possible reason for getting an empty result could be that there are no collinear blocks between the particular source and target that you have selected. Alternatively, some alignments may have been ignored because they are not in the right format. When uploading the files can you select the option "No" for the two questions on the upload page and try again.
> 
> I can also debug the issue for you at my end, If you can share the collinearity and gff file that you used. Finally, sometimes an empty result can also be due to format issues in the uploaded file so I have linked a [sample collinearity](https://github.com/kiranbandi/synvisio/blob/master/build/assets/files/bn_collinear.collinearity), [gff](https://github.com/kiranbandi/synvisio/blob/master/build/assets/files/bn_coordinate.gff), and [track file](https://github.com/kiranbandi/synvisio/blob/master/build/assets/files/bn_gene_count.txt) for your reference.
> 
> Thanks,
> Kiran

Hi @kiranbandi ,

Yes, your advice solved my question perfectly. While a new issue appeared that I found a repetitive scale on the scaleplate as below,
![image](https://user-images.githubusercontent.com/44871713/86217527-2d7d9880-bbb2-11ea-8216-ef7d86fa0de6.png)

So is this a multi-mapped condition for this chromosome, or something else?  

Thanks,
Yung

**Comment by kiranbandi** [comment]
@Yung-Chien 

This is not a multimapped condition and seems like a bug in the system. The scales are created automatically and then rounded up to the nearest integer which is why you are seeing repeated number when in reality the values would be 8.1 and 8.8 instead of 8 and 8. I have added this issue to our bug list and will fix it in the next patch. For now you can hide the scale by using the checkbox "show marker scales". sorry for the confusion and thanks again for pointing it out. 

Kiran
