### ISSUE TITLE
multi-Level Analysis view

### ISSUE THREAD

**Issue by fafuyyk** [kiranbandi/synvisio#35]
Hi ,

Hello, I am using SynVisio in a comparative genomics database I am developing, but I want to enable my customers to see a multi-Level Analysis view when opening SynVisio on the website. What I mean is that multiple Chromosome levels are pre-set in the opened interface, and the user can see a multi-level Tree view by clicking the button.

How should I do it, adjust parameters, or secondary development. If you know where to modify it, I'd love to let me know. thank you very much!

**Comment by kiranbandi** [comment]
There is an initialState file in the redux folder that is used to set the defaults for redux store, it can be found at - https://github.com/kiranbandi/synvisio/blob/master/src/redux/reducers/initialState.jsx

These defaults set in this object decide the state of the application.  Setting the multiLevel flag to "true" on line 12
https://github.com/kiranbandi/synvisio/blob/3415935bf3bb95b156eaf108cd9d2e764e5a7d72/src/redux/reducers/initialState.jsx#L12
should make SynVisio load in the Multi-Level Analysis view. There is also a corresponding key multiLevelType in the same object that decides which multi level analysis mode is selected. It defaults to "tree" which I believe is what you want so you can leave that unchanged. 

Then the default chromosomes that are selected in the filter panel need to be set in the sampleSourceMapper File -
https://github.com/kiranbandi/synvisio/blob/master/src/utils/sampleSourceMapper.js
set the default value as an array so it should have keys 0,1,2 instead of the "source" and "target" that we have now. 

I think these changes should be enough for what you want to achieve.
