### ISSUE TITLE
Source or Target Empty for long time

### ISSUE THREAD

**Issue by kashiff007** [kiranbandi/synvisio#38]
Hi, Thanks for making this fantastic tool.

I have a concern regarding the time to show Source or Target chromosomes. I have my collinearity file of 90 MB, but the chromosome names are not showing in the synteny dashboard. I have waited for more than 10hr.

However, the uploading doesn't take much time successfully uploaded.

**Comment by kiranbandi** [comment]
Hi,

SynVisio by default filters out chromosomes/regions that dont match the standard chromosome format and tags them as scaffolds. 
In your case it's highly likely that all the chromosomes/regions in your input files were tagged as scaffolds and filtered out and thus not available as an option for Source or Target selection.

To fix this on the upload page, you can simply set the answer to the question "Would you like to ignore Scaffold regions ?" as "No" this will ensure they are preserved and available for selection on the dashboard.

**Comment by kashiff007** [comment]
Thanks for the response @kiranbandi 
In my case I don’t have any scaffolds. I have 20 chromosomes named as chr1A, chr1B, chr2A, chr2B … till chr10A and chr10B. Could you describe what do you mean by “standard chromosome format” ? I am wondering my chromosome names may have any problem.

**Comment by kiranbandi** [comment]
Even if you don't have scaffolds in your data, SynVisio mistakenly assumes your chromosomes are scaffolds because of their naming pattern. Hence answering "No" to the question "Would you like to ignore Scaffold regions ?" will ensure the chromosomes are preserved. A standard chromosome format is a 2 character identifier followed by a number. So for example chromosomes 1 and 2 of _Brassica napus_ (Canola) would be BN1 and BN2.

**Comment by kashiff007** [comment]
Thanks for your support its working now.
